# Generated by Django 5.1.4 on 2025-04-05 23:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Recipe', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='authorID',
            new_name='author',
        ),
    ]
